In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.shape

(4803, 20)

In [4]:
credits.shape

(4803, 4)

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [6]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [7]:
#credit and movies merged using their ids
merge_df = pd.merge(movies, credits, left_on = 'id' , right_on = 'movie_id', how = 'inner')
merge_df.shape

(4803, 24)

In [8]:
merge_df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [9]:
#imp columns separated from the df and made new_df
new_df = merge_df[['id' , 'genres', 'keywords' , 'overview' , 'production_companies' , 'title_x', 'cast' , 'crew']]

In [10]:
new_df

,id,genres,keywords,overview,production_companies,title_x,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""name"": ""Ingenious Film Partners"", ""id"": 289...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4798,9367,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],A newlywed couple's honeymoon is upended by th...,[],Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""name"": ""Front Street Pictures"", ""id"": 3958}...","Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,[],[],When ambitious New York attorney Sam is sent t...,[],Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [11]:
#renamed column name as per convenience
new_df = new_df.rename(columns = {'title_x':'title'})

In [12]:
(new_df.loc[0, 'keywords'])

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [13]:
#abstract syntax tree
import  ast
x = ast.literal_eval(new_df.loc[0, 'keywords'])
x

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

In [14]:

#by making function define
import ast 
def get_names(obj):
    x = ast.literal_eval(obj)
    keywords =[]
    for r in x:
        name = r['name'].replace(" ", "_").lower().strip() #to make tags, we added '_' to each string so it becomes a single string as tag
        if name not in keywords:
            keywords.append(name)
    return ",".join(keywords)

In [15]:
new_df['keywords'] = new_df['keywords'].apply(get_names)

In [16]:
new_df['genres'] = new_df['genres'].apply(get_names)

In [17]:
new_df['cast'] = new_df['cast'].apply(get_names)

In [18]:
new_df['crew'] = new_df['crew'].apply(get_names)

In [19]:
new_df['production_companies'] = new_df['production_companies'].apply(get_names)

In [20]:
new_df.head(1)

,id,genres,keywords,overview,production_companies,title,cast,crew
0,19995,"action,adventure,fantasy,science_fiction","culture_clash,future,space_war,space_colony,so...","In the 22nd century, a paraplegic Marine is di...","ingenious_film_partners,twentieth_century_fox_...",Avatar,"sam_worthington,zoe_saldana,sigourney_weaver,s...","stephen_e._rivkin,rick_carter,christopher_boye..."

In [21]:
#lambda-apply given operation on each record in respective column
new_df['overview'] = new_df['overview'].apply(lambda x:str(x).replace(",","").replace(" ",",").lower())
new_df['overview']

0       in,the,22nd,century,a,paraplegic,marine,is,dis...
1       captain,barbossa,long,believed,to,be,dead,has,...
2       a,cryptic,message,from,bondâ€™s,past,sends,him,o...
3       following,the,death,of,district,attorney,harve...
4       john,carter,is,a,war-weary,former,military,cap...
                              ...
4798    el,mariachi,just,wants,to,play,his,guitar,and,...
4799    a,newlywed,couple's,honeymoon,is,upended,by,th...
4800    "signed,sealed,delivered",introduces,a,dedicat...
4801    when,ambitious,new,york,attorney,sam,is,sent,t...
4802    ever,since,the,second,grade,when,he,first,saw,...
Name: overview, Length: 4803, dtype: object

In [22]:
new_df['tags'] = new_df['genres'] + "," +  new_df['keywords']  + "," +  new_df['overview'] + "," +  new_df['cast'] + "," +  new_df['crew'] + "," + new_df['production_companies']
new_df

,id,genres,keywords,overview,production_companies,title,cast,crew,tags
0,19995,"action,adventure,fantasy,science_fiction","culture_clash,future,space_war,space_colony,so...","in,the,22nd,century,a,paraplegic,marine,is,dis...","ingenious_film_partners,twentieth_century_fox_...",Avatar,"sam_worthington,zoe_saldana,sigourney_weaver,s...","stephen_e._rivkin,rick_carter,christopher_boye...","action,adventure,fantasy,science_fiction,cultu..."
1,285,"adventure,fantasy,action","ocean,drug_abuse,exotic_island,east_india_trad...","captain,barbossa,long,believed,to,be,dead,has,...","walt_disney_pictures,jerry_bruckheimer_films,s...",Pirates of the Caribbean: At World's End,"johnny_depp,orlando_bloom,keira_knightley,stel...","dariusz_wolski,gore_verbinski,jerry_bruckheime...","adventure,fantasy,action,ocean,drug_abuse,exot..."
2,206647,"action,adventure,crime","spy,based_on_novel,secret_agent,sequel,mi6,bri...","a,cryptic,message,from,bondâ€™s,past,sends,him,o...","columbia_pictures,danjaq,b24",Spectre,"daniel_craig,christoph_waltz,lÃ©a_seydoux,ralph...","thomas_newman,sam_mendes,anna_pinnock,john_log...","action,adventure,crime,spy,based_on_novel,secr..."
3,49026,"action,crime,drama,thriller","dc_comics,crime_fighter,terrorist,secret_ident...","following,the,death,of,district,attorney,harve...","legendary_pictures,warner_bros.,dc_entertainme...",The Dark Knight Rises,"christian_bale,michael_caine,gary_oldman,anne_...","hans_zimmer,charles_roven,christopher_nolan,jo...","action,crime,drama,thriller,dc_comics,crime_fi..."
4,49529,"action,adventure,science_fiction","based_on_novel,mars,medallion,space_travel,pri...","john,carter,is,a,war-weary,former,military,cap...",walt_disney_pictures,John Carter,"taylor_kitsch,lynn_collins,samantha_morton,wil...","andrew_stanton,john_lasseter,colin_wilson,gail...","action,adventure,science_fiction,based_on_nove..."
...,...,...,...,...,...,...,...,...,...
4798,9367,"action,crime,thriller","united_statesâ€“mexico_barrier,legs,arms,paper_k...","el,mariachi,just,wants,to,play,his,guitar,and,...",columbia_pictures,El Mariachi,"carlos_gallardo,jaime_de_hoyos,peter_marquardt...","robert_rodriguez,carlos_gallardo,eric_guthrie,...","action,crime,thriller,united_statesâ€“mexico_bar..."
4799,72766,"comedy,romance",,"a,newlywed,couple's,honeymoon,is,upended,by,th...",,Newlyweds,"edward_burns,kerry_bishÃ©,marsha_dietlein,caitl...","edward_burns,william_rexer,p.t._walkley,janet_...","comedy,romance,,a,newlywed,couple's,honeymoon,..."
4800,231617,"comedy,drama,romance,tv_movie","date,love_at_first_sight,narration,investigati...","""signed,sealed,delivered"",introduces,a,dedicat...","front_street_pictures,muse_entertainment_enter...","Signed, Sealed, Delivered","eric_mabius,kristin_booth,crystal_lowe,geoff_g...","carla_hetland,harvey_kahn,adam_sliwinski,marth...","comedy,drama,romance,tv_movie,date,love_at_fir..."
4801,126186,,,"when,ambitious,new,york,attorney,sam,is,sent,t...",,Shanghai Calling,"daniel_henney,eliza_coupe,bill_paxton,alan_ruc...",daniel_hsia,",,when,ambitious,new,york,attorney,sam,is,sent..."
4802,25975,documentary,"obsession,camcorder,crush,dream_girl","ever,since,the,second,grade,when,he,first,saw,...","rusty_bear_entertainment,lucky_crow_films",My Date with Drew,"drew_barrymore,brian_herzlinger,corey_feldman,...","clark_peterson,andrew_reimer,brian_herzlinger,...","documentary,obsession,camcorder,crush,dream_gi..."

In [23]:
final_df = new_df[["id", "title", "tags"]]
final_df

,id,title,tags
0,19995,Avatar,"action,adventure,fantasy,science_fiction,cultu..."
1,285,Pirates of the Caribbean: At World's End,"adventure,fantasy,action,ocean,drug_abuse,exot..."
2,206647,Spectre,"action,adventure,crime,spy,based_on_novel,secr..."
3,49026,The Dark Knight Rises,"action,crime,drama,thriller,dc_comics,crime_fi..."
4,49529,John Carter,"action,adventure,science_fiction,based_on_nove..."
...,...,...,...
4798,9367,El Mariachi,"action,crime,thriller,united_statesâ€“mexico_bar..."
4799,72766,Newlyweds,"comedy,romance,,a,newlywed,couple's,honeymoon,..."
4800,231617,"Signed, Sealed, Delivered","comedy,drama,romance,tv_movie,date,love_at_fir..."
4801,126186,Shanghai Calling,",,when,ambitious,new,york,attorney,sam,is,sent..."
4802,25975,My Date with Drew,"documentary,obsession,camcorder,crush,dream_gi..."

In [24]:
final_df.dropna(inplace = True)

In [26]:
final_df.drop_duplicates(inplace = True)

In [29]:
pip install nltk

Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: click in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.5.1)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.5 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 4.3 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl (273 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, nltk

   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ------------- -------------------------- 1/3 [regex]
   ------------- -------------------------- 1/3 [regex]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]

Successfully installed nltk-3.9.1 regex-2024.11.6 tqdm-4.67.1
Note: you may need to restart the kernel to use updated packages.

In [31]:
#remove stopwords natural language toolkit
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
#download stopwords if not alredy exists
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1028)>
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1028)>
[nltk_data] Error loading punkt_tab: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1028)>

False

In [32]:
def remove_stop_words(text):
    #get the english stopword list
    stop_words = set(stopwords.words('english'))
    #tokenize the sentence
    words = text.split(',')
    #remove stopwords
    filtered_words = [word for word in words if word.lower() not in stop_words]
    #convert back to string
    filtered_text = ','.join(filtered_words)
    return filtered_text

In [ ]:
final_df['tags'] = final_df['tags'].apply(remove_stop_words)

In [ ]:
final_df.info()

In [ ]:
final_df

In [ ]:
final_df.to_csv("cleaned_data.csv")